SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS comboMenuItems;
DROP TABLE IF EXISTS comboMenus;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nameCro VARCHAR(100) NOT NULL,
    nameEn VARCHAR(100) NOT NULL,
    sortOrder INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE dishes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    categoryId INT NOT NULL,
    dishNumber VARCHAR(10) DEFAULT NULL,
    nameCro TEXT NOT NULL,
    nameEn TEXT NOT NULL,
    price DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    sortOrder INT DEFAULT 0,
    FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comboMenus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    nameCro VARCHAR(200) NOT NULL,
    nameEn VARCHAR(200) NOT NULL,
    personCount INT NOT NULL,
    price DECIMAL(8,2) NOT NULL,
    sortOrder INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comboMenuItems (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comboMenuId INT NOT NULL,
    itemNumber INT NOT NULL,
    nameCro TEXT NOT NULL,
    nameEn TEXT NOT NULL,
    sortOrder INT DEFAULT 0,
    FOREIGN KEY (comboMenuId) REFERENCES comboMenus(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
